### ISSUE TITLE
Cannot Get All Food 

### ISSUE THREAD

**Issue by ezerssss** [charmaine-aguilar/filipino-foods-api#1]
![image](https://user-images.githubusercontent.com/72904036/204424505-d03bb257-765c-4685-860c-2cf928460140.png)

Steps to reproduce:

- Fetch `https://filipino-foods-api.herokuapp.com/api`

**Comment by charmaine-aguilar** [comment]
Hello, @ezerssss! Thank you for noticing that. I updated everything and you should be able to access all the food and specific food now. Please let me know if any more issue arises. Thank you!
